name: codecov

on:
  push:
    branches: [ master ]
    paths:
    - 'bin/**'
    - 'src/**'
    - 'include/**'
    - 'partial/**'
    - 'tests/**'
    - '.github/workflows/codecov.yml'
    - 'Makefile'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: update apt
        run: sudo apt-get update

      - name: install dependencies
        run: sudo apt-get install -y libidn2-0-dev libidn11-dev

      - name: make coverage (libidn2)
        run: make coverage FORCE_IDN=idn2

      - name: upload codecov (libidn2)
        uses: codecov/codecov-action@v3
        with:
          name: ubuntu-latest-libidn2
          fail_ci_if_error: true
          verbose: true
          gcov: true
          gcov_ignore: tests
          flags: core,libidn2

      - name: make clean
        run: make clean FORCE_IDN=idn2

      - name: make coverage (libidn)
        run: make coverage FORCE_IDN=idn

      - name: upload codecov (libidn)
        uses: codecov/codecov-action@v3
        with:
          name: ubuntu-latest-libidn
          fail_ci_if_error: true
          verbose: true
          gcov: true
          gcov_ignore: tests
          flags: core,libidn
