name: codecov

on:
  push:
    branches: [ master ]
    paths:
    - 'bin/**'
    - 'src/**'
    - 'include/**'
    - 'partial/**'
    - 'tests/**'
    - '.github/**'
    - 'Makefile'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  libidn2:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: update apt
        run: sudo apt-get update

      # gcovr pkg was added since 18.04LTS
      - name: install gcovr
        run: sudo apt-get install -y gcovr

      - name: install dependencies
        run: sudo apt-get install -y libidn2-0 libidn2-0-dev

      - name: make coverage
        run: make coverage

      - name: upload codecov
        uses: codecov/codecov-action@v3
        with:
          name: ubuntu-latest-libidn2
          fail_ci_if_error: true
          verbose: true
          gcov: true
          gcov_ignore: tests
          flags: core,libidn2
