name: codecov

on:
  push:
    branches: [ master ]
    paths:
    - 'bin/**'
    - 'src/**'
    - 'include/**'
    - 'partial/**'
    - 'tests/**'
    - '.github/workflows/codecov.yml'
    - 'Makefile'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: update apt
        run: sudo apt-get update

      - name: install dependencies
        run: sudo apt-get install -y libidn2-0-dev libidn11-dev

      - name: make coverage (libidn2)
        run: make coverage FORCE_IDN=idn2

      - name: upload codecov (libidn2)
        uses: codecov/codecov-action@v3
        with:
          name: ubuntu-latest-libidn2
          fail_ci_if_error: true
          verbose: true
          gcov: true
          gcov_ignore: tests
          flags: core,libidn2

      - name: make clean (libidn2)
        run: make clean FORCE_IDN=idn2

      - name: make coverage (libidn)
        run: make coverage FORCE_IDN=idn

      - name: upload codecov (libidn)
        uses: codecov/codecov-action@v3
        with:
          name: ubuntu-latest-libidn
          fail_ci_if_error: true
          verbose: true
          gcov: true
          gcov_ignore: tests
          flags: core,libidn

      - name: make clean (libidn)
        run: make clean FORCE_IDN=idn

      - name: download idnkit
        run: curl -Os -L https://jprs.co.jp/idn/idnkit-2.3.tar.bz2

      - name: unpack idnkit
        run: tar xjvf idnkit-2.3.tar.bz2

      # indkit's tests prerequisites:
      #   apt-get install libxml-simple-perl
      #   sed -i 's,^# ja_JP.EUC-JP EUC-JP,ja_JP.EUC-JP EUC-JP,' /etc/locale.gen
      #   sed -i 's,^# ja_JP.UTF-8 UTF-8,ja_JP.UTF-8 UTF-8,' /etc/locale.gen
      #
      #   # already done on github servers
      #   apt-get install libc6-dev
      - name: install XML::Simple for Perl
        run: sudo apt-get install libxml-simple-perl -y

      - name: create ja_JP locale
        run: |
          sudo sed -i 's,^# ja_JP.EUC-JP EUC-JP,ja_JP.EUC-JP EUC-JP,' /etc/locale.gen
          sudo sed -i 's,^# ja_JP.UTF-8 UTF-8,ja_JP.UTF-8 UTF-8,' /etc/locale.gen
          sudo locale-gen

      - name: build idnkit
        run: |
          cd idnkit-2.3
          ./configure --prefix=$HOME/local
          make
          make check
          make install
          cd ..

      - name: make coverage (idnkit)
        run: make coverage FORCE_IDN=idnkit IDNKIT_DIR=$HOME/local

      - name: upload codecov (idnkit)
        uses: codecov/codecov-action@v3
        with:
          name: ubuntu-latest-idnkit
          fail_ci_if_error: true
          verbose: true
          gcov: true
          gcov_ignore: tests
          flags: core,idnkit
